disabled_rules:
  - trailing_whitespace
  - file_length
  - type_body_length
  - function_body_length
  - function_parameter_count
opt_in_rules:
  - explicit_top_level_acl
  - force_unwrapping
included:
  - Source
